apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudbilling-api.fullname" . }}-dbstring
  labels:
    {{- include "cloudbilling-api.labels" . | nindent 4 }}
    version: {{ .Values.secretfile.version }}
type: Opaque
data:
  dbstring: {{ .Files.Get ".cloudbilling-api.dbstring" | b64enc }}